### ISSUE TITLE
box-sizing of sp-container content not working well with Bootstrap 3

### ISSUE THREAD

**Issue by bertpareyn** [bgrins/spectrum#175]
The box-sizing that bootstrap adds to elements does not work well for spectrum. The fix is simple and added below.

Before:
![screen shot 2014-02-05 at 15 27 49](https://f.cloud.github.com/assets/218391/2088343/2bf3a1ba-8e7a-11e3-9484-f2beb3248183.png)

After applying:

``` css
.sp-container *,
.sp-container *:after,
.sp-container *:before {
    -webkit-box-sizing: content-box;
       -moz-box-sizing: content-box;
            box-sizing: content-box;
}
```

![screen shot 2014-02-05 at 15 27 58](https://f.cloud.github.com/assets/218391/2088342/2bf19f1e-8e7a-11e3-91c6-278a3f2a6b9f.png)
