### ISSUE TITLE
Show picker above instead of below

### ISSUE THREAD

**Issue by skitterm** [bgrins/spectrum#445]
I'd like to show the color picker above the element that opens it, instead of below. Is there a way of doing that? I thought I could be real smart and calculate the height of the picker in the beforeShow function, but of course it's not displayed yet (so doesn't have its height/width yet).

**Comment by jcubic** [comment]
You probably can use appendTo option to append to the container that wraps your input, set position: relative on container and put
```css
.sp-container {
 bottom: 100% !important;
 left: 0 !important;
 top: auto !important;
}
```
one problem is that you will need to set the width, change the size in developer tools and set the same value in css (no need to use important).
